let employeeName = "John Mayor";
const employeeID = 12575;
var isActive = true;
console.log(employeeName, typeof employeeName);
console.log(employeeID, typeof employeeID);
console.log(isActive, typeof isActive);
let productName = "Computer";
const productPrice = 689.99;
var isAvailable = true;
console.log(productName, typeof productName); 
console.log(productPrice, typeof productPrice); 
console.log(isAvailable, typeof isAvailable); 
let accountBalance = 6700;  
accountBalance += 3000; 
console.log(accountBalance);
accountBalance -= 600; 
console.log(accountBalance); 
accountBalance *= 2.05; 
console.log(accountBalance);
accountBalance /= 2; 
console.log(accountBalance); 
let customerName = "Alice";
let welcomeMessage = "Hello, " + customerName + "! Welcome to our store.";
console.log(welcomeMessage);