let employeeName = "John Mayor";
const employeeID = 12575;
var isActive = true;
console.log(employeeName, typeof employeeName);
console.log(employeeID, typeof employeeID);
console.log(isActive, typeof isActive);
let productName = "Computer";
const productPrice = 689.99;
var isAvailable = true;
console.log(productName, typeof productName); 
console.log(productPrice, typeof productPrice); 
console.log(isAvailable, typeof isAvailable);   